flags: {}
packages:
- '.'
extra-deps:
 - git: https://github.com/remeike/fn-monadic
   commit: 2365dd816915548833b453c3d53f3addedbb3f16
   subdirs:
    - fn-monadic
 - git: https://github.com/positiondev/larceny
   commit: 494dcf620577f96bc797f1ba7f75d9053079c12f

resolver: lts-20.26
